/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.daos;


import docrep.db.tables.Account;
import docrep.db.tables.records.AccountRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountDao extends DAOImpl<AccountRecord, docrep.db.tables.pojos.Account, Integer> {

    /**
     * Create a new AccountDao without any configuration
     */
    public AccountDao() {
        super(Account.ACCOUNT, docrep.db.tables.pojos.Account.class);
    }

    /**
     * Create a new AccountDao with an attached configuration
     */
    public AccountDao(Configuration configuration) {
        super(Account.ACCOUNT, docrep.db.tables.pojos.Account.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(docrep.db.tables.pojos.Account object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Account> fetchById(Integer... values) {
        return fetch(Account.ACCOUNT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public docrep.db.tables.pojos.Account fetchOneById(Integer value) {
        return fetchOne(Account.ACCOUNT.ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Account> fetchByUsername(String... values) {
        return fetch(Account.ACCOUNT.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public docrep.db.tables.pojos.Account fetchOneByUsername(String value) {
        return fetchOne(Account.ACCOUNT.USERNAME, value);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Account> fetchByPassword(String... values) {
        return fetch(Account.ACCOUNT.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>last_login_date IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Account> fetchByLastLoginDate(Timestamp... values) {
        return fetch(Account.ACCOUNT.LAST_LOGIN_DATE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Account> fetchByStatus(String... values) {
        return fetch(Account.ACCOUNT.STATUS, values);
    }

    /**
     * Fetch records that have <code>person_id IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Account> fetchByPersonId(Integer... values) {
        return fetch(Account.ACCOUNT.PERSON_ID, values);
    }
}
