/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.daos;


import docrep.db.tables.Address;
import docrep.db.tables.records.AddressRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressDao extends DAOImpl<AddressRecord, docrep.db.tables.pojos.Address, Integer> {

    /**
     * Create a new AddressDao without any configuration
     */
    public AddressDao() {
        super(Address.ADDRESS, docrep.db.tables.pojos.Address.class);
    }

    /**
     * Create a new AddressDao with an attached configuration
     */
    public AddressDao(Configuration configuration) {
        super(Address.ADDRESS, docrep.db.tables.pojos.Address.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(docrep.db.tables.pojos.Address object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Address> fetchById(Integer... values) {
        return fetch(Address.ADDRESS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public docrep.db.tables.pojos.Address fetchOneById(Integer value) {
        return fetchOne(Address.ADDRESS.ID, value);
    }

    /**
     * Fetch records that have <code>street_name IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Address> fetchByStreetName(String... values) {
        return fetch(Address.ADDRESS.STREET_NAME, values);
    }

    /**
     * Fetch records that have <code>building_number IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Address> fetchByBuildingNumber(String... values) {
        return fetch(Address.ADDRESS.BUILDING_NUMBER, values);
    }

    /**
     * Fetch records that have <code>premises_number IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Address> fetchByPremisesNumber(String... values) {
        return fetch(Address.ADDRESS.PREMISES_NUMBER, values);
    }

    /**
     * Fetch records that have <code>postal_code IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Address> fetchByPostalCode(String... values) {
        return fetch(Address.ADDRESS.POSTAL_CODE, values);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Address> fetchByCity(String... values) {
        return fetch(Address.ADDRESS.CITY, values);
    }
}
