/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.daos;


import docrep.db.tables.Contact;
import docrep.db.tables.records.ContactRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactDao extends DAOImpl<ContactRecord, docrep.db.tables.pojos.Contact, Integer> {

    /**
     * Create a new ContactDao without any configuration
     */
    public ContactDao() {
        super(Contact.CONTACT, docrep.db.tables.pojos.Contact.class);
    }

    /**
     * Create a new ContactDao with an attached configuration
     */
    public ContactDao(Configuration configuration) {
        super(Contact.CONTACT, docrep.db.tables.pojos.Contact.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(docrep.db.tables.pojos.Contact object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Contact> fetchById(Integer... values) {
        return fetch(Contact.CONTACT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public docrep.db.tables.pojos.Contact fetchOneById(Integer value) {
        return fetchOne(Contact.CONTACT.ID, value);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Contact> fetchByValue(String... values) {
        return fetch(Contact.CONTACT.VALUE, values);
    }

    /**
     * Fetch records that have <code>regexp IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Contact> fetchByRegexp(String... values) {
        return fetch(Contact.CONTACT.REGEXP, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Contact> fetchByDescription(String... values) {
        return fetch(Contact.CONTACT.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Contact> fetchByType(String... values) {
        return fetch(Contact.CONTACT.TYPE, values);
    }

    /**
     * Fetch records that have <code>person_id IN (values)</code>
     */
    public List<docrep.db.tables.pojos.Contact> fetchByPersonId(Integer... values) {
        return fetch(Contact.CONTACT.PERSON_ID, values);
    }
}
