/*
 * This file is generated by jOOQ.
*/
package docrep.db;


import docrep.db.tables.Account;
import docrep.db.tables.Address;
import docrep.db.tables.Contact;
import docrep.db.tables.Document;
import docrep.db.tables.Person;
import docrep.db.tables.StorageLocation;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PKEY = Indexes0.ACCOUNT_PKEY;
    public static final Index ACCOUNT_USERNAME_KEY = Indexes0.ACCOUNT_USERNAME_KEY;
    public static final Index ADDRESS_PKEY = Indexes0.ADDRESS_PKEY;
    public static final Index CONTACT_PKEY = Indexes0.CONTACT_PKEY;
    public static final Index DOCUMENT_PKEY = Indexes0.DOCUMENT_PKEY;
    public static final Index PERSON_PKEY = Indexes0.PERSON_PKEY;
    public static final Index STORAGE_LOCATION_PKEY = Indexes0.STORAGE_LOCATION_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ACCOUNT_PKEY = createIndex("account_pkey", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ID }, true);
        public static Index ACCOUNT_USERNAME_KEY = createIndex("account_username_key", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.USERNAME }, true);
        public static Index ADDRESS_PKEY = createIndex("address_pkey", Address.ADDRESS, new OrderField[] { Address.ADDRESS.ID }, true);
        public static Index CONTACT_PKEY = createIndex("contact_pkey", Contact.CONTACT, new OrderField[] { Contact.CONTACT.ID }, true);
        public static Index DOCUMENT_PKEY = createIndex("document_pkey", Document.DOCUMENT, new OrderField[] { Document.DOCUMENT.ID }, true);
        public static Index PERSON_PKEY = createIndex("person_pkey", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
        public static Index STORAGE_LOCATION_PKEY = createIndex("storage_location_pkey", StorageLocation.STORAGE_LOCATION, new OrderField[] { StorageLocation.STORAGE_LOCATION.ID }, true);
    }
}
