/*
 * This file is generated by jOOQ.
*/
package docrep.db;


import docrep.db.tables.Account;
import docrep.db.tables.Address;
import docrep.db.tables.Contact;
import docrep.db.tables.Document;
import docrep.db.tables.Person;
import docrep.db.tables.Phrasetable;
import docrep.db.tables.StorageLocation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1749218701;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = docrep.db.tables.Account.ACCOUNT;

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = docrep.db.tables.Address.ADDRESS;

    /**
     * The table <code>public.contact</code>.
     */
    public final Contact CONTACT = docrep.db.tables.Contact.CONTACT;

    /**
     * The table <code>public.document</code>.
     */
    public final Document DOCUMENT = docrep.db.tables.Document.DOCUMENT;

    /**
     * The table <code>public.person</code>.
     */
    public final Person PERSON = docrep.db.tables.Person.PERSON;

    /**
     * The table <code>public.phrasetable</code>.
     */
    public final Phrasetable PHRASETABLE = docrep.db.tables.Phrasetable.PHRASETABLE;

    /**
     * The table <code>public.storage_location</code>.
     */
    public final StorageLocation STORAGE_LOCATION = docrep.db.tables.StorageLocation.STORAGE_LOCATION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACCOUNT_ID_SEQ,
            Sequences.ADDRESS_ID_SEQ,
            Sequences.CONTACT_ID_SEQ,
            Sequences.DOCUMENT_ID_SEQ,
            Sequences.PERSON_ID_SEQ,
            Sequences.STORAGE_LOCATION_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Address.ADDRESS,
            Contact.CONTACT,
            Document.DOCUMENT,
            Person.PERSON,
            Phrasetable.PHRASETABLE,
            StorageLocation.STORAGE_LOCATION);
    }
}
