/*
 * This file is generated by jOOQ.
*/
package docrep.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.account_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNT_ID_SEQ = new SequenceImpl<Long>("account_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.address_id_seq</code>
     */
    public static final Sequence<Long> ADDRESS_ID_SEQ = new SequenceImpl<Long>("address_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.contact_id_seq</code>
     */
    public static final Sequence<Long> CONTACT_ID_SEQ = new SequenceImpl<Long>("contact_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.document_id_seq</code>
     */
    public static final Sequence<Long> DOCUMENT_ID_SEQ = new SequenceImpl<Long>("document_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.person_id_seq</code>
     */
    public static final Sequence<Long> PERSON_ID_SEQ = new SequenceImpl<Long>("person_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.storage_location_id_seq</code>
     */
    public static final Sequence<Long> STORAGE_LOCATION_ID_SEQ = new SequenceImpl<Long>("storage_location_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
