/*
 * This file is generated by jOOQ.
*/
package docrep.db;


import docrep.db.tables.Account;
import docrep.db.tables.Address;
import docrep.db.tables.Contact;
import docrep.db.tables.Document;
import docrep.db.tables.Person;
import docrep.db.tables.Phrasetable;
import docrep.db.tables.StorageLocation;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = docrep.db.tables.Account.ACCOUNT;

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = docrep.db.tables.Address.ADDRESS;

    /**
     * The table <code>public.contact</code>.
     */
    public static final Contact CONTACT = docrep.db.tables.Contact.CONTACT;

    /**
     * The table <code>public.document</code>.
     */
    public static final Document DOCUMENT = docrep.db.tables.Document.DOCUMENT;

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = docrep.db.tables.Person.PERSON;

    /**
     * The table <code>public.phrasetable</code>.
     */
    public static final Phrasetable PHRASETABLE = docrep.db.tables.Phrasetable.PHRASETABLE;

    /**
     * The table <code>public.storage_location</code>.
     */
    public static final StorageLocation STORAGE_LOCATION = docrep.db.tables.StorageLocation.STORAGE_LOCATION;
}
