/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.records;


import docrep.db.tables.Address;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -470060978;

    /**
     * Setter for <code>public.address.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.address.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.address.street_name</code>.
     */
    public void setStreetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.address.street_name</code>.
     */
    public String getStreetName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.address.building_number</code>.
     */
    public void setBuildingNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.address.building_number</code>.
     */
    public String getBuildingNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.address.premises_number</code>.
     */
    public void setPremisesNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.address.premises_number</code>.
     */
    public String getPremisesNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.address.postal_code</code>.
     */
    public void setPostalCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.address.postal_code</code>.
     */
    public String getPostalCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.address.city</code>.
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.address.city</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Address.ADDRESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Address.ADDRESS.STREET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Address.ADDRESS.BUILDING_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Address.ADDRESS.PREMISES_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Address.ADDRESS.POSTAL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Address.ADDRESS.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStreetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBuildingNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPremisesNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStreetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBuildingNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPremisesNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value2(String value) {
        setStreetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value3(String value) {
        setBuildingNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value4(String value) {
        setPremisesNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value5(String value) {
        setPostalCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value6(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Integer id, String streetName, String buildingNumber, String premisesNumber, String postalCode, String city) {
        super(Address.ADDRESS);

        set(0, id);
        set(1, streetName);
        set(2, buildingNumber);
        set(3, premisesNumber);
        set(4, postalCode);
        set(5, city);
    }
}
