/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.records;


import docrep.db.tables.StorageLocation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StorageLocationRecord extends UpdatableRecordImpl<StorageLocationRecord> implements Record8<Integer, String, String, Double, Double, Integer, String, Integer> {

    private static final long serialVersionUID = 1150602086;

    /**
     * Setter for <code>public.storage_location.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.storage_location.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.storage_location.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.storage_location.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.storage_location.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.storage_location.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.storage_location.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.storage_location.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.storage_location.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.storage_location.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.storage_location.superior_storage_loc_id</code>.
     */
    public void setSuperiorStorageLocId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.storage_location.superior_storage_loc_id</code>.
     */
    public Integer getSuperiorStorageLocId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.storage_location.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.storage_location.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.storage_location.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.storage_location.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Double, Double, Integer, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Double, Double, Integer, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StorageLocation.STORAGE_LOCATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StorageLocation.STORAGE_LOCATION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StorageLocation.STORAGE_LOCATION.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return StorageLocation.STORAGE_LOCATION.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return StorageLocation.STORAGE_LOCATION.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return StorageLocation.STORAGE_LOCATION.SUPERIOR_STORAGE_LOC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return StorageLocation.STORAGE_LOCATION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return StorageLocation.STORAGE_LOCATION.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSuperiorStorageLocId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSuperiorStorageLocId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord value4(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord value5(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord value6(Integer value) {
        setSuperiorStorageLocId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord value7(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord value8(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageLocationRecord values(Integer value1, String value2, String value3, Double value4, Double value5, Integer value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StorageLocationRecord
     */
    public StorageLocationRecord() {
        super(StorageLocation.STORAGE_LOCATION);
    }

    /**
     * Create a detached, initialised StorageLocationRecord
     */
    public StorageLocationRecord(Integer id, String name, String description, Double longitude, Double latitude, Integer superiorStorageLocId, String type, Integer accountId) {
        super(StorageLocation.STORAGE_LOCATION);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, longitude);
        set(4, latitude);
        set(5, superiorStorageLocId);
        set(6, type);
        set(7, accountId);
    }
}
