/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = -1406621374;

    private Integer   id;
    private String    username;
    private String    password;
    private Timestamp lastLoginDate;
    private String    status;
    private Integer   personId;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.lastLoginDate = value.lastLoginDate;
        this.status = value.status;
        this.personId = value.personId;
    }

    public Account(
        Integer   id,
        String    username,
        String    password,
        Timestamp lastLoginDate,
        String    status,
        Integer   personId
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.lastLoginDate = lastLoginDate;
        this.status = status;
        this.personId = personId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Timestamp getLastLoginDate() {
        return this.lastLoginDate;
    }

    public void setLastLoginDate(Timestamp lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getPersonId() {
        return this.personId;
    }

    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(lastLoginDate);
        sb.append(", ").append(status);
        sb.append(", ").append(personId);

        sb.append(")");
        return sb.toString();
    }
}
