/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document implements Serializable {

    private static final long serialVersionUID = -1829528645;

    private Integer   id;
    private String    number;
    private String    title;
    private String    barcode;
    private Timestamp registerDate;
    private Integer   storageLocationId;
    private Integer   ownerId;
    private String    description;
    private Integer   version;
    private Timestamp editDate;

    public Document() {}

    public Document(Document value) {
        this.id = value.id;
        this.number = value.number;
        this.title = value.title;
        this.barcode = value.barcode;
        this.registerDate = value.registerDate;
        this.storageLocationId = value.storageLocationId;
        this.ownerId = value.ownerId;
        this.description = value.description;
        this.version = value.version;
        this.editDate = value.editDate;
    }

    public Document(
        Integer   id,
        String    number,
        String    title,
        String    barcode,
        Timestamp registerDate,
        Integer   storageLocationId,
        Integer   ownerId,
        String    description,
        Integer   version,
        Timestamp editDate
    ) {
        this.id = id;
        this.number = number;
        this.title = title;
        this.barcode = barcode;
        this.registerDate = registerDate;
        this.storageLocationId = storageLocationId;
        this.ownerId = ownerId;
        this.description = description;
        this.version = version;
        this.editDate = editDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public Timestamp getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(Timestamp registerDate) {
        this.registerDate = registerDate;
    }

    public Integer getStorageLocationId() {
        return this.storageLocationId;
    }

    public void setStorageLocationId(Integer storageLocationId) {
        this.storageLocationId = storageLocationId;
    }

    public Integer getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Timestamp getEditDate() {
        return this.editDate;
    }

    public void setEditDate(Timestamp editDate) {
        this.editDate = editDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Document (");

        sb.append(id);
        sb.append(", ").append(number);
        sb.append(", ").append(title);
        sb.append(", ").append(barcode);
        sb.append(", ").append(registerDate);
        sb.append(", ").append(storageLocationId);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(description);
        sb.append(", ").append(version);
        sb.append(", ").append(editDate);

        sb.append(")");
        return sb.toString();
    }
}
