/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Phrasetable implements Serializable {

    private static final long serialVersionUID = 1094672758;

    private Object phrase;

    public Phrasetable() {}

    public Phrasetable(Phrasetable value) {
        this.phrase = value.phrase;
    }

    public Phrasetable(
        Object phrase
    ) {
        this.phrase = phrase;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getPhrase() {
        return this.phrase;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setPhrase(Object phrase) {
        this.phrase = phrase;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Phrasetable (");

        sb.append(phrase);

        sb.append(")");
        return sb.toString();
    }
}
