/*
 * This file is generated by jOOQ.
*/
package docrep.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StorageLocation implements Serializable {

    private static final long serialVersionUID = 1073831593;

    private Integer id;
    private String  name;
    private String  description;
    private Double  longitude;
    private Double  latitude;
    private Integer superiorStorageLocId;
    private String  type;
    private Integer accountId;

    public StorageLocation() {}

    public StorageLocation(StorageLocation value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.longitude = value.longitude;
        this.latitude = value.latitude;
        this.superiorStorageLocId = value.superiorStorageLocId;
        this.type = value.type;
        this.accountId = value.accountId;
    }

    public StorageLocation(
        Integer id,
        String  name,
        String  description,
        Double  longitude,
        Double  latitude,
        Integer superiorStorageLocId,
        String  type,
        Integer accountId
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.longitude = longitude;
        this.latitude = latitude;
        this.superiorStorageLocId = superiorStorageLocId;
        this.type = type;
        this.accountId = accountId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Integer getSuperiorStorageLocId() {
        return this.superiorStorageLocId;
    }

    public void setSuperiorStorageLocId(Integer superiorStorageLocId) {
        this.superiorStorageLocId = superiorStorageLocId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StorageLocation (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(longitude);
        sb.append(", ").append(latitude);
        sb.append(", ").append(superiorStorageLocId);
        sb.append(", ").append(type);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
